"""Add table role

Revision ID: 527058e6cc8c
Revises: 0c0a9e34e5b4
Create Date: 2023-06-21 03:16:28.303492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527058e6cc8c'
down_revision = '0c0a9e34e5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
